import type { LucideIcon } from 'lucide-react';
import {
  BookOpen, FileEdit, Video, Library, Bus, Heart, CalendarCheck, Megaphone,
  Calendar, MessageSquare, CreditCard, Award, BarChart3, Layers, Upload,
  Bell, Target, ArrowUpDown, ClipboardList, ClipboardCheck, Monitor, Fingerprint,
  Briefcase, TrendingUp, Notebook, Download, Package, History, Building2,
  Sparkles, Brain, Clock, ListChecks, Settings, CheckCircle2, Shield, Users,
  GraduationCap, Search, FileText, ScanText,
} from 'lucide-react';

export interface FeatureDef {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
}

export const PLATFORM_FEATURES: FeatureDef[] = [
  { id: 'exams', label: 'Examinations & Tests', icon: FileEdit, description: 'Create and manage exams, tests, and quizzes' },
  { id: 'homework', label: 'Homework', icon: BookOpen, description: 'Assign and track homework submissions' },
  { id: 'video_lessons', label: 'Video Lessons', icon: Video, description: 'Video, text, audio, and image lessons' },
  { id: 'live_classes', label: 'Live Classes', icon: Video, description: 'Real-time virtual classrooms with video, chat, whiteboard' },
  { id: 'library', label: 'Library', icon: Library, description: 'Book catalog and borrow records' },
  { id: 'transport', label: 'Transport', icon: Bus, description: 'School transport routes and stops' },
  { id: 'health_records', label: 'Health Records', icon: Heart, description: 'Student health and medical records' },
  { id: 'attendance', label: 'Attendance', icon: CalendarCheck, description: 'Daily attendance tracking' },
  { id: 'staff_attendance', label: 'Staff Attendance', icon: Fingerprint, description: 'Staff check-in/out attendance' },
  { id: 'announcements', label: 'Announcements', icon: Megaphone, description: 'School-wide announcements' },
  { id: 'calendar', label: 'Calendar & Events', icon: Calendar, description: 'School calendar and events' },
  { id: 'timetable', label: 'Timetable', icon: Clock, description: 'Class scheduling and timetables' },
  { id: 'scheme_of_work', label: 'Scheme of Work', icon: ListChecks, description: 'Curriculum planning and scheme of work' },
  { id: 'feedback', label: 'Feedback', icon: MessageSquare, description: 'Student and parent feedback system' },
  { id: 'chat', label: 'Messaging / Chat', icon: MessageSquare, description: 'In-app messaging system' },
  { id: 'report_cards', label: 'Report Cards', icon: Award, description: 'Generate and publish report cards' },
  { id: 'behavior', label: 'Behavior Tracking', icon: Target, description: 'Student behavior and discipline records' },
  { id: 'achievements', label: 'Achievements & Badges', icon: Award, description: 'Student badges and achievements' },
  { id: 'parent_portal', label: 'Parent Portal', icon: Users, description: 'Parent access to child data' },
  { id: 'notifications', label: 'Notifications', icon: Bell, description: 'Push and in-app notifications' },
  { id: 'support_tickets', label: 'Support Tickets', icon: Settings, description: 'Technical support requests' },
  { id: 'analytics', label: 'Analytics & Reports', icon: BarChart3, description: 'Performance analytics dashboards' },
  { id: 'bulk_operations', label: 'Bulk Operations', icon: Layers, description: 'Bulk import/export/updates' },
  { id: 'data_import_export', label: 'Data Import/Export', icon: Upload, description: 'Import and export data files' },
  { id: 'advanced_search', label: 'Advanced Search', icon: Search, description: 'Advanced search across all data' },
  { id: 'student_promotion', label: 'Student Promotion', icon: ArrowUpDown, description: 'Promote students to next class' },
  { id: 'grading', label: 'Grading System', icon: ClipboardList, description: 'Score entry and grade management' },
  { id: 'lesson_plans', label: 'Lesson Plans', icon: BookOpen, description: 'Teacher lesson planning tools' },
  { id: 'fee_management', label: 'Fee Management', icon: CreditCard, description: 'Fee structure and payments' },
  { id: 'weekly_evaluations', label: 'Weekly Evaluations', icon: ClipboardCheck, description: 'Weekly student evaluations by teachers' },
  { id: 'class_monitoring', label: 'Class Monitoring', icon: Monitor, description: 'Real-time class activity monitoring' },
  { id: 'entrance_exams', label: 'Entrance Exams', icon: FileEdit, description: 'School entrance exam management' },
  { id: 'job_postings', label: 'Careers & Jobs', icon: Briefcase, description: 'Job postings and career management' },
  { id: 'student_diary', label: 'Student Diary', icon: Notebook, description: 'Personal student diary/journal' },
  { id: 'ai_assistant', label: 'AI Teaching Assistant', icon: Brain, description: 'AI-powered teaching tools and assistant' },
  { id: 'ai_grading', label: 'AI Grading', icon: Sparkles, description: 'Automated AI grading of assignments' },
  { id: 'ai_timetable_generator', label: 'AI Timetable Generator', icon: Sparkles, description: 'AI-powered timetable creation' },
  { id: 'ai_scheme_of_work_generator', label: 'AI Scheme of Work', icon: Sparkles, description: 'AI-generated curriculum schemes' },
  { id: 'ai_lesson_note_generator', label: 'AI Lesson Note Generator', icon: Sparkles, description: 'AI-powered lesson plan creation' },
  { id: 'ai_homework_generator', label: 'AI Homework Generator', icon: Sparkles, description: 'AI-generated homework assignments' },
  { id: 'ai_report_card_writer', label: 'AI Report Card Writer', icon: Sparkles, description: 'AI-generated report card comments' },
  { id: 'ai_pd_planner', label: 'AI PD Planner', icon: Brain, description: 'AI-powered professional development plans' },
  { id: 'ai_admin_dashboard', label: 'AI Admin Intel', icon: Brain, description: 'AI analytics, forecasts, and insights for admins' },
  { id: 'teacher_tasks', label: 'Teacher Tasks', icon: ListChecks, description: 'Task management for teachers' },
  { id: 'teacher_performance', label: 'Teacher Performance', icon: TrendingUp, description: 'Teacher performance tracking' },
  { id: 'student_leaderboard', label: 'Leaderboard', icon: Award, description: 'Gamification and student leaderboards' },
  { id: 'lesson_progress', label: 'Lesson Progress Reports', icon: BarChart3, description: 'Track lesson and learning progress' },
  { id: 'testimonials', label: 'Testimonials', icon: MessageSquare, description: 'School testimonials management' },
  { id: 'trusted_schools', label: 'Trusted Schools', icon: Shield, description: 'Trusted school listing management' },
  { id: 'payment_verification', label: 'Payment Verification', icon: CheckCircle2, description: 'Payment approval workflow' },
  { id: 'student_lesson_notes', label: 'Lesson Notes', icon: BookOpen, description: 'Lesson notes for students' },
  { id: 'parent_downloads', label: 'Parent Downloads', icon: Download, description: 'Parent report download access' },
  { id: 'hostels', label: 'Hostel Management', icon: Building2, description: 'Hostel allocation and room management' },
  { id: 'inventory', label: 'Inventory Management', icon: Package, description: 'School asset and inventory tracking' },
  { id: 'alumni', label: 'Alumni Management', icon: GraduationCap, description: 'Alumni records and event management' },
  { id: 'clubs', label: 'Clubs & Societies', icon: Users, description: 'Student clubs and membership management' },
  { id: 'enrollment_history', label: 'Enrollment History', icon: History, description: 'Student enrollment change history' },
  { id: 'documents', label: 'Document Templates', icon: FileText, description: 'Pre-built school document templates and editor' },
  { id: 'ocr_scanner', label: 'OCR Scanner', icon: ScanText, description: 'Scan physical documents and extract text via OCR' },
];

export const PLATFORM_FEATURE_IDS = PLATFORM_FEATURES.map(f => f.id);
export type FeatureId = (typeof PLATFORM_FEATURES)[number]['id'];

export const USER_ROLES = [
  { id: 'SCHOOL_ADMIN', label: 'School Admin', icon: Shield, description: 'School administrators' },
  { id: 'TEACHER', label: 'Teacher', icon: GraduationCap, description: 'Teaching staff' },
  { id: 'STUDENT', label: 'Student', icon: GraduationCap, description: 'Students' },
  { id: 'PARENT', label: 'Parent', icon: Users, description: 'Parents and guardians' },
  { id: 'ACCOUNTANT', label: 'Accountant', icon: CreditCard, description: 'Financial staff' },
  { id: 'LIBRARIAN', label: 'Librarian', icon: Library, description: 'Library staff' },
  { id: 'DIRECTOR', label: 'Director', icon: Shield, description: 'School directors' },
] as const;

export type RoleId = (typeof USER_ROLES)[number]['id'];

export const viewToFeatureMap: Record<string, FeatureId> = {
  'video-lessons': 'video_lessons',
  'live-classes': 'live_classes',
  'staff-attendance': 'staff_attendance',
  'timetable': 'timetable',
  'scheme-of-work': 'scheme_of_work',
  'class-monitoring': 'class_monitoring',
  'entrance-exams': 'entrance_exams',
  'job-postings': 'job_postings',
  'student-diary': 'student_diary',
  'ai-assistant': 'ai_assistant',
  'ai-grading': 'ai_grading',
  'teacher-tasks': 'teacher_tasks',
  'teacher-my-tasks': 'teacher_tasks',
  'teacher-performance': 'teacher_performance',
  'student-leaderboard': 'student_leaderboard',
  'lesson-progress-reports': 'lesson_progress',
  'testimonials': 'testimonials',
  'trusted-schools': 'trusted_schools',
  'payment-verification': 'payment_verification',
  'student-lesson-notes': 'student_lesson_notes',
  'parent-lesson-notes': 'student_lesson_notes',
  'parent-download-reports': 'parent_downloads',
  'weekly-evaluations': 'weekly_evaluations',
  'report-cards': 'report_cards',
  'health-records': 'health_records',
  'data-import': 'data_import_export',
  'advanced-search': 'advanced_search',
  'student-promotion': 'student_promotion',
  'student-ai-chat': 'ai_assistant',
  'lesson-plans': 'lesson_plans',
  'school-calendar-enhanced': 'calendar',
  'in-app-chat': 'chat',
  'messaging-center': 'chat',
  'teacher-grades': 'grading',
  'bulk-operations': 'bulk_operations',
  'fee-structure': 'fee_management',
  'parent-portal': 'parent_portal',
  'admin-analytics-advanced': 'analytics',
  'school-comparison': 'analytics',
  'books': 'library',
  'borrow-records': 'library',
  'support': 'support_tickets',
  'hostels': 'hostels',
  'inventory': 'inventory',
  'alumni': 'alumni',
  'clubs': 'clubs',
  'enrollment-history': 'enrollment_history',
  'ai-timetable-generator': 'ai_timetable_generator',
  'ai-scheme-of-work-generator': 'ai_scheme_of_work_generator',
  'ai-lesson-note-generator': 'ai_lesson_note_generator',
  'ai-homework-generator': 'ai_homework_generator',
  'ai-report-card-writer': 'ai_report_card_writer',
  'ai-pd-planner': 'ai_pd_planner',
  'ai-admin-dashboard': 'ai_admin_dashboard',
  'documents': 'documents',
  'ocr-scanner': 'ocr_scanner',
};
