FROM node:20-alpine AS runner
WORKDIR /app
RUN npm install -g tsx
COPY package.json package-lock.json ./
RUN npm ci
COPY prisma ./prisma
RUN npx prisma generate
COPY . .
EXPOSE 3003
CMD ["tsx", "server/index.ts"]
