'use client';

import { useState, useEffect } from 'react';

interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const languages: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo' },
];

export const RTL_LANGUAGES = ['ar'];
export function isRtl(lang: string) { return RTL_LANGUAGES.includes(lang); }

export const timezones: LanguageOption[] = [
  { code: 'lagos', name: 'West Africa Time', nativeName: 'WAT (UTC+1)' },
  { code: 'london', name: 'Greenwich Mean Time', nativeName: 'GMT (UTC+0)' },
  { code: 'dubai', name: 'Gulf Standard Time', nativeName: 'GST (UTC+4)' },
  { code: 'nairobi', name: 'East Africa Time', nativeName: 'EAT (UTC+3)' },
];

export const currencies: LanguageOption[] = [
  { code: 'ngn', name: 'Nigerian Naira', nativeName: '₦' },
  { code: 'usd', name: 'US Dollar', nativeName: '$' },
  { code: 'gbp', name: 'British Pound', nativeName: '£' },
  { code: 'eur', name: 'Euro', nativeName: '€' },
];

export function useLanguage() {
  const [language, setLanguage] = useState<string>('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadLanguage() {
      try {
        const res = await fetch('/api/user-preferences');
        if (res.ok) {
          const data = await res.json();
          if (data.data?.language) {
            setLanguage(data.data.language);
          }
        }
      } catch {
        // Use default
      } finally {
        setLoading(false);
      }
    }
    loadLanguage();
  }, []);

  const saveLanguage = async (lang: string) => {
    try {
      const res = await fetch('/api/user-preferences', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ language: lang }),
      });
      if (res.ok) {
        setLanguage(lang);
      }
    } catch {
      // Silent fail
    }
  };

  const getLanguageName = (code: string) => {
    const lang = languages.find(l => l.code === code);
    return lang?.name || code;
  };

  const getNativeName = (code: string) => {
    const lang = languages.find(l => l.code === code);
    return lang?.nativeName || code;
  };

  return {
    language,
    loading,
    saveLanguage,
    getLanguageName,
    getNativeName,
    languages,
  };
}

export const translations: Record<string, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'An error occurred',
    success: 'Success',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    reset: 'Reset',
    view: 'View',
    duplicate: 'Duplicate',
    deactivate: 'Deactivate',
    activate: 'Activate',
    refresh: 'Refresh',
    publish: 'Publish',
    unpublish: 'Unpublish',
    saveDraft: 'Save Draft',
    preview: 'Preview',
    hidePreview: 'Hide Preview',
    showPreview: 'Show Preview',
    generate: 'Generate',
    generating: 'Generating...',
    setup: 'Setup',
    bulkImport: 'Bulk Import',
    addQuestion: 'Add Question',
    deleteSelected: 'Delete Selected',
    deleteAll: 'Delete All',
    deactivateQuestion: 'Deactivate Question',
    deactivateSelected: 'Deactivate Selected Questions',
    deactivateAll: 'Deactivate All Questions',
    confirmDeactivate: 'This will deactivate the question. It will no longer appear in the bank but existing references remain.',
    confirmDeactivateSelected: 'This will deactivate {count} question(s). They will no longer appear in the bank but existing references remain.',
    confirmDeactivateAll: 'This will deactivate all {count} active questions in the bank. Existing references in exams and homework will remain. This action cannot be undone.',
    heroSection: 'Hero Section',
    aboutPage: 'About Page',
    admissionsPage: 'Admissions Page',
    contactInfo: 'Contact Information',
    featureCards: 'Feature Cards',
    extraContent: 'Extra Content Blocks',
    sectionVisibility: 'Section Visibility',
    seoSettings: 'SEO Settings',
    theme: 'Theme',
    schoolSettings: 'School Settings',
    advancedSettings: 'Advanced Settings',
    customCss: 'Custom CSS',
    schoolWebsite: 'School Website',
    questionBank: 'Question Bank',
    active: 'Active',
    inactive: 'Inactive',
    total: 'Total',
    allSubjects: 'All Subjects',
    allClasses: 'All Classes',
    allTopics: 'All Topics',
    allTypes: 'All Types',
    allLevels: 'All Levels',
    searchQuestions: 'Search questions...',
    dashboard: 'Dashboard',
    students: 'Students',
    teachers: 'Teachers',
    classes: 'Classes',
    subjects: 'Subjects',
    exams: 'Exams',
    homework: 'Homework',
    attendance: 'Attendance',
    fees: 'Fees',
    reports: 'Reports',
    messages: 'Messages',
    announcements: 'Announcements',
    calendar: 'Calendar',
    timetable: 'Timetable',
    library: 'Library',
    transport: 'Transport',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    profile: 'Profile',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    french: 'French',
    haus: 'Hausa',
    yoruba: 'Yoruba',
    igbo: 'Igbo',
    questionText: 'Question',
    options: 'Options',
    correctAnswer: 'Correct Answer',
    marks: 'Marks',
    difficulty: 'Difficulty',
    subject: 'Subject',
    class: 'Class',
    topic: 'Topic',
    type: 'Type',
    createdBy: 'Created By',
    status: 'Status',
    actions: 'Actions',
    viewSite: 'View Site',
    heroTitle: 'Hero Title',
    heroSubtitle: 'Hero Subtitle',
    heroBackgroundImage: 'Hero Background Image',
    aboutPageTitle: 'About Page Title',
    aboutContent: 'About Content',
    admissionsPageTitle: 'Admissions Page Title',
    admissionsContent: 'Admissions Content',
    contactEmail: 'Contact Email',
    contactPhone: 'Contact Phone',
    contactAddress: 'Contact Address',
    socialMediaLinks: 'Social Media Links',
    metaTitle: 'Meta Title',
    metaDescription: 'Meta Description',
    schoolName: 'School Name',
    websiteSlug: 'Website Slug',
    schoolLogo: 'School Logo',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    schoolMotto: 'School Motto',
    schoolType: 'School Type',
    foundedDate: 'Founded Date',
    schoolEmail: 'School Email',
    schoolPhone: 'School Phone',
    schoolAddress: 'School Address',
    nurseryPrimary: 'Nursery & Primary',
    secondaryOnly: 'Secondary Only',
    primarySecondary: 'Primary & Secondary',
    higherInstitution: 'Higher Institution',
    questionPreview: 'Question Preview',
    explanation: 'Explanation',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    multipleChoice: 'Multiple Choice',
    multiSelect: 'Multi-Select',
    trueFalse: 'True/False',
    fillBlank: 'Fill Blank',
    shortAnswer: 'Short Answer',
    essay: 'Essay',
    matching: 'Matching',
    downloadCsvTemplate: 'Download CSV Template',
    uploadCsv: 'Upload CSV',
    valid: 'valid',
    invalid: 'invalid',
    rows: 'rows',
    of: 'of',
    selected: 'selected',
    page: 'Page',
    all: 'All',
    noActiveQuestions: 'No active questions to delete',
    changesSaved: 'Changes saved',
    websitePublished: 'Website published!',
    websiteUnpublished: 'Website unpublished',
    setupComplete: 'Setup complete! You can continue editing below.',
    contentGenerated: 'Content generated!',
    failedToLoad: 'Failed to load',
    failedToSave: 'Failed to save',
    failedToPublish: 'Failed to publish',
    failedToDelete: 'Failed to delete',
    slugAvailable: 'Available',
    slugTaken: 'Taken',
    slugInvalid: 'Invalid format',
    slugChangeWarning: 'Changing the slug will change your website URL. Old links will break.',
    generateWarning: 'This will replace all existing website content with auto-generated content based on your school type. Any custom content you have written will be overwritten. Continue?',
    allSectionsHidden: 'All sections are hidden. Enable them in the Section Visibility tab.',
    portalLogin: 'Portal Login',
    poweredBy: 'Powered by',
    allRightsReserved: 'All rights reserved.',
    quickLinks: 'Quick Links',
    email: 'Email',
    phone: 'Phone',
    schoolEmail: 'School Email',
    schoolPhone: 'School Phone',
    home: 'Home',
    aboutUs: 'About Us',
    contact: 'Contact',
    learnMore: 'Learn More',
    applyNow: 'Apply Now',
    readMore: 'Read More',
    admissionsOpen: 'Admissions Open',
    joinCommunity: 'Join our community of learners. Applications are now being accepted.',
    welcomeTo: 'Welcome to {name}',
    buildingFuture: 'Building the future through quality education',
    aboutPrefix: 'About',
    studentsExcellence: 'Excellence',
    communityTogether: 'Together We Grow',
    curriculumComprehensive: 'Comprehensive',
    achievementRecognition: 'Recognition',
    advancedSettings: 'Advanced Settings',
  },
  ar: {
    welcome: 'مرحباً',
    settings: 'الإعدادات',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    error: 'حدث خطأ',
    success: 'تم بنجاح',
    confirm: 'تأكيد',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    submit: 'إرسال',
    reset: 'إعادة تعيين',
    view: 'عرض',
    duplicate: 'نسخ',
    deactivate: 'إلغاء تنشيط',
    activate: 'تنشيط',
    refresh: 'تحديث',
    publish: 'نشر',
    unpublish: 'إلغاء النشر',
    saveDraft: 'حفظ المسودة',
    preview: 'معاينة',
    hidePreview: 'إخفاء المعاينة',
    showPreview: 'إظهار المعاينة',
    generate: 'توليد',
    generating: 'جارٍ التوليد...',
    setup: 'إعداد',
    bulkImport: 'استيراد جماعي',
    addQuestion: 'إضافة سؤال',
    deleteSelected: 'حذف المحدد',
    deleteAll: 'حذف الكل',
    deactivateQuestion: 'إلغاء تنشيط السؤال',
    deactivateSelected: 'إلغاء تنشيط الأسئلة المحددة',
    deactivateAll: 'إلغاء تنشيط جميع الأسئلة',
    confirmDeactivate: 'سيؤدي هذا إلى إلغاء تنشيط السؤال. لن يظهر في البنك بعد الآن ولكن المراجع الحالية ستبقى.',
    confirmDeactivateSelected: 'سيؤدي هذا إلى إلغاء تنشيط {count} سؤال. لن تظهر في البنك بعد الآن ولكن المراجع الحالية ستبقى.',
    confirmDeactivateAll: 'سيؤدي هذا إلى إلغاء تنشيط جميع الأسئلة النشطة البالغ عددها {count} في البنك. ستبقى المراجع الحالية في الامتحانات والواجبات المنزلية. لا يمكن التراجع عن هذا الإجراء.',
    heroSection: 'قسم البطل',
    aboutPage: 'صفحة عن المدرسة',
    admissionsPage: 'صفحة القبول',
    contactInfo: 'معلومات الاتصال',
    featureCards: 'بطاقات الميزات',
    extraContent: 'كتل المحتوى الإضافية',
    sectionVisibility: 'رؤية الأقسام',
    seoSettings: 'إعدادات تحسين محركات البحث',
    theme: 'السمة',
    schoolSettings: 'إعدادات المدرسة',
    advancedSettings: 'الإعدادات المتقدمة',
    customCss: 'CSS مخصص',
    schoolWebsite: 'موقع المدرسة',
    questionBank: 'بنك الأسئلة',
    active: 'نشط',
    inactive: 'غير نشط',
    total: 'المجموع',
    allSubjects: 'جميع المواد',
    allClasses: 'جميع الفصول',
    allTopics: 'جميع المواضيع',
    allTypes: 'جميع الأنواع',
    allLevels: 'جميع المستويات',
    searchQuestions: 'البحث عن أسئلة...',
    dashboard: 'لوحة التحكم',
    students: 'الطلاب',
    teachers: 'المعلمون',
    classes: 'الفصول',
    subjects: 'المواد',
    exams: 'الامتحانات',
    homework: 'الواجبات المنزلية',
    attendance: 'الحضور',
    fees: 'الرسوم',
    reports: 'التقارير',
    messages: 'الرسائل',
    announcements: 'الإعلانات',
    calendar: 'التقويم',
    timetable: 'الجدول الزمني',
    library: 'المكتبة',
    transport: 'النقل',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    register: 'التسجيل',
    profile: 'الملف الشخصي',
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    french: 'الفرنسية',
    haus: 'الهوسا',
    yoruba: 'اليورuba',
    igbo: 'الإيغو',
    questionText: 'السؤال',
    options: 'الخيارات',
    correctAnswer: 'الإجابة الصحيحة',
    marks: 'الدرجات',
    difficulty: 'الصعوبة',
    subject: 'المادة',
    class: 'الفصل',
    topic: 'الموضوع',
    type: 'النوع',
    createdBy: 'أنشأه',
    status: 'الحالة',
    actions: 'الإجراءات',
    viewSite: 'عرض الموقع',
    heroTitle: 'عنوان البطل',
    heroSubtitle: 'عنوان فرعي للبطل',
    heroBackgroundImage: 'صورة خلفية البطل',
    aboutPageTitle: 'عنوان صفحة من نحن',
    aboutContent: 'محتوى من نحن',
    admissionsPageTitle: 'عنوان صفحة القبول',
    admissionsContent: 'محتوى القبول',
    contactEmail: 'بريد الاتصال',
    contactPhone: 'هاتف الاتصال',
    contactAddress: 'عنوان الاتصال',
    socialMediaLinks: 'روابط التواصل الاجتماعي',
    metaTitle: 'عنوان SEO',
    metaDescription: 'وصف SEO',
    schoolName: 'اسم المدرسة',
    websiteSlug: 'رابط الموقع',
    schoolLogo: 'شعار المدرسة',
    primaryColor: 'اللون الأساسي',
    secondaryColor: 'اللون الثانوي',
    schoolMotto: 'شعار المدرسة',
    schoolType: 'نوع المدرسة',
    foundedDate: 'تاريخ التأسيس',
    schoolEmail: 'بريد المدرسة',
    schoolPhone: 'هاتف المدرسة',
    schoolAddress: 'عنوان المدرسة',
    nurseryPrimary: 'روضة وابتدائي',
    secondaryOnly: 'ثانوي فقط',
    primarySecondary: 'ابتدائي وثانوي',
    higherInstitution: 'مؤسسة عليا',
    questionPreview: 'معاينة السؤال',
    explanation: 'التوضيح',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    multipleChoice: 'اختيار متعدد',
    multiSelect: 'اختيار متعدد',
    trueFalse: 'صحيح/خطأ',
    fillBlank: 'ملء الفراغ',
    shortAnswer: 'إجابة قصيرة',
    essay: 'مقال',
    matching: 'مطابقة',
    downloadCsvTemplate: 'تحميل نموذج CSV',
    uploadCsv: 'رفع CSV',
    valid: 'صالح',
    invalid: 'غير صالح',
    rows: 'صفوف',
    of: 'من',
    selected: 'محدد',
    page: 'صفحة',
    all: 'الكل',
    noActiveQuestions: 'لا توجد أسئلة نشطة للحذف',
    changesSaved: 'تم حفظ التغييرات',
    websitePublished: 'تم نشر الموقع!',
    websiteUnpublished: 'تم إلغاء نشر الموقع',
    setupComplete: 'اكتمل الإعداد! يمكنك المتابعة في التعديل أدناه.',
    contentGenerated: 'تم توليد المحتوى!',
    failedToLoad: 'فشل التحميل',
    failedToSave: 'فشل الحفظ',
    failedToPublish: 'فشل النشر',
    failedToDelete: 'فشل الحذف',
    slugAvailable: 'متاح',
    slugTaken: 'محجوز',
    slugInvalid: 'تنسيق غير صالح',
    slugChangeWarning: 'تغيير الرابط سيغير عنوان موقعك. الروابط القديمة ستتوقف.',
    generateWarning: 'سيؤدي هذا إلى استبدال جميع محتويات الموقع بمحتوى مولد تلقائياً بناءً على نوع مدرستك. أي محتوى مخصص كتبته سيتم الكتابة فوقه. هل تريد المتابعة؟',
    allSectionsHidden: 'جميع الأقسام مخفية. قم بتشغيلها في تبويب رؤية الأقسام.',
    portalLogin: 'دخول البوابة',
    poweredBy: 'مدعوم oleh',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    quickLinks: 'روابط سريعة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    schoolEmail: 'بريد المدرسة',
    schoolPhone: 'هاتف المدرسة',
    home: 'الرئيسية',
    aboutUs: 'عن المدرسة',
    contact: 'اتصل بنا',
    learnMore: 'اعرف المزيد',
    applyNow: 'تقدم الآن',
    readMore: 'اقرأ المزيد',
    admissionsOpen: 'القبول مفتوح',
    joinCommunity: 'انضم إلى مجتمعنا من المتعلمين. يتم قبول الطلبات الآن.',
    welcomeTo: 'مرحباً بك في {name}',
    buildingFuture: 'نبني المستقبل من خلال التعليم_quality',
    aboutPrefix: 'عن',
    studentsExcellence: 'التميز',
    communityTogether: 'معاً ننمو',
    curriculumComprehensive: 'شامل',
    achievementRecognition: 'تقدير',
  },
  fr: {
    welcome: 'Bienvenue',
    settings: 'Paramètres',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    loading: 'Chargement...',
    noData: 'Aucune donnée disponible',
    error: 'Une erreur est survenue',
    success: 'Succès',
    confirm: 'Confirmer',
    close: 'Fermer',
    back: 'Retour',
    next: 'Suivant',
    submit: 'Soumettre',
    reset: 'Réinitialiser',
    view: 'Voir',
    duplicate: 'Dupliquer',
    deactivate: 'Désactiver',
    activate: 'Activer',
    refresh: 'Actualiser',
    publish: 'Publier',
    unpublish: 'Dépublier',
    saveDraft: 'Enregistrer le brouillon',
    preview: 'Aperçu',
    hidePreview: "Masquer l'aperçu",
    showPreview: "Afficher l'aperçu",
    generate: 'Générer',
    generating: 'Génération...',
    setup: 'Configurer',
    bulkImport: 'Import en masse',
    addQuestion: 'Ajouter une question',
    deleteSelected: 'Supprimer la sélection',
    deleteAll: 'Tout supprimer',
    deactivateQuestion: 'Désactiver la question',
    deactivateSelected: 'Désactiver les questions sélectionnées',
    deactivateAll: 'Désactiver toutes les questions',
    confirmDeactivate: "Cela désactivera la question. Elle n'apparaîtra plus dans la banque mais les références existantes resteront.",
    confirmDeactivateSelected: "Cela désactivera {count} question(s). Elles n'apparaîtront plus dans la banque mais les références existantes resteront.",
    confirmDeactivateAll: "Cela désactivera toutes les {count} questions actives de la banque. Les références existantes dans les examens et devoirs resteront. Cette action est irréversible.",
    heroSection: 'Section Hero',
    aboutPage: 'Page À propos',
    admissionsPage: 'Page Admissions',
    contactInfo: 'Informations de contact',
    featureCards: 'Cartes de fonctionnalités',
    extraContent: 'Blocs de contenu supplémentaires',
    sectionVisibility: 'Visibilité des sections',
    seoSettings: 'Paramètres SEO',
    theme: 'Thème',
    schoolSettings: 'Paramètres de l\'école',
    advancedSettings: 'Paramètres avancés',
    customCss: 'CSS personnalisé',
    schoolWebsite: 'Site web de l\'école',
    questionBank: 'Banque de questions',
    active: 'Actif',
    inactive: 'Inactif',
    total: 'Total',
    allSubjects: 'Toutes les matières',
    allClasses: 'Toutes les classes',
    allTopics: 'Tous les sujets',
    allTypes: 'Tous les types',
    allLevels: 'Tous les niveaux',
    searchQuestions: 'Rechercher des questions...',
    dashboard: 'Tableau de bord',
    students: 'Élèves',
    teachers: 'Enseignants',
    classes: 'Classes',
    subjects: 'Matières',
    exams: 'Examens',
    homework: 'Devoirs',
    attendance: 'Présence',
    fees: 'Frais',
    reports: 'Rapports',
    messages: 'Messages',
    announcements: 'Annonces',
    calendar: 'Calendrier',
    timetable: 'Emploi du temps',
    library: 'Bibliothèque',
    transport: 'Transport',
    login: 'Connexion',
    logout: 'Déconnexion',
    register: "S'inscrire",
    profile: 'Profil',
    language: 'Langue',
    english: 'Anglais',
    arabic: 'Arabe',
    french: 'Français',
    login: 'Connexion',
    logout: 'Déconnexion',
    register: "S'inscrire",
    questionText: 'Question',
    options: 'Options',
    correctAnswer: 'Réponse correcte',
    marks: 'Points',
    difficulty: 'Difficulté',
    subject: 'Matière',
    class: 'Classe',
    topic: 'Sujet',
    type: 'Type',
    createdBy: 'Créé par',
    status: 'Statut',
    actions: 'Actions',
    viewSite: 'Voir le site',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    multipleChoice: 'Choix multiple',
    multiSelect: 'Multi-sélection',
    trueFalse: 'Vrai/Faux',
    fillBlank: 'Texte à trous',
    shortAnswer: 'Réponse courte',
    essay: 'Dissertation',
    matching: 'Appariement',
    downloadCsvTemplate: 'Télécharger le modèle CSV',
    uploadCsv: 'Télécharger CSV',
    valid: 'valide',
    invalid: 'invalide',
    rows: 'lignes',
    of: 'sur',
    selected: 'sélectionné',
    page: 'Page',
    all: 'Tout',
    home: 'Accueil',
    aboutUs: 'À propos',
    contact: 'Contact',
    learnMore: 'En savoir plus',
    applyNow: 'Postuler maintenant',
    readMore: 'Lire la suite',
    admissionsOpen: 'Admissions ouvertes',
    joinCommunity: 'Rejoignez notre communauté d\'apprenants. Les candidatures sont maintenant acceptées.',
    welcomeTo: 'Bienvenue à {name}',
    buildingFuture: 'Construire l\'avenir par l\'éducation de qualité',
    portalLogin: 'Connexion au portail',
    poweredBy: 'Propulsé par',
    allRightsReserved: 'Tous droits réservés.',
    quickLinks: 'Liens rapides',
    email: 'E-mail',
    phone: 'Téléphone',
    schoolEmail: 'E-mail de l\'école',
    schoolPhone: 'Téléphone de l\'école',
    home: 'Accueil',
    aboutUs: 'À propos de nous',
    contact: 'Contact',
    learnMore: 'En savoir plus',
    applyNow: 'Postuler maintenant',
    readMore: 'Lire la suite',
    admissionsOpen: 'Admissions ouvertes',
    joinCommunity: 'Rejoignez notre communauté.',
    welcomeTo: 'Bienvenue à {name}',
    buildingFuture: 'Bâtir l\'avenir par l\'éducation.',
  },
  ha: {
    welcome: 'Maraba',
    settings: 'Saituna',
    save: 'Ajiye',
    cancel: 'Soke',
    delete: 'Share',
    edit: 'Gyara',
    add: 'Kara',
    search: 'Nema',
    filter: 'Tace',
    export: 'Fitarwa',
    import: 'Shigo',
    loading: 'Ana lodawa...',
    noData: 'Babu bayani',
    error: 'An samu kuskure',
    success: 'Nasara',
    confirm: 'Tabbatar',
    close: 'Rufe',
    back: 'Koma',
    next: 'Gaba',
    submit: 'Tura',
    reset: 'Sake',
    view: 'Duba',
    duplicate: 'Kwatanta',
    deactivate: 'Soke aiki',
    activate: 'Fara aiki',
    refresh: 'Sabunta',
    publish: 'Bugawa',
    unpublish: 'Soke bugawa',
    saveDraft: 'Ajiye karatu',
    preview: 'Duba kafin',
    hidePreview: 'Boye duba kafin',
    showPreview: 'Nuna duba kafin',
    generate: 'Samar da',
    generating: 'Ana samar da...',
    setup: 'Saita',
    bulkImport: 'Shigo da yawa',
    addQuestion: 'Ƙara tambaya',
    deleteSelected: 'Share da aka zaɓa',
    deleteAll: 'Share duka',
    deactivateQuestion: 'Soke aikin tambaya',
    deactivateSelected: 'Soke tambayoyin da aka zaɓa',
    deactivateAll: 'Soke dukkan tambayoyi',
    confirmDeactivate: 'Wannan zai soke aikin tambaya. Ba za ta bayyana a bankin ba amma references na yanzu za su ci gaba.',
    confirmDeactivateSelected: 'Wannan zai soke tambayoyi {count}. Ba za su bayyana a bankin ba amma references na yanzu za su ci gaba.',
    confirmDeactivateAll: 'Wannan zai soke dukkan tambayoyi {count} a bankin. References na yanzu a cikin imtihani da homework za su ci gaba. Ba za a iya soke wannan aikin ba.',
    heroSection: 'Sashen Hero',
    aboutPage: 'Shafin Game da',
    admissionsPage: 'Shafin Karbuwa',
    contactInfo: 'Bayanan Tuntuɓi',
    featureCards: 'Katunan Fasali',
    extraContent: 'Tantanin Halin Cikin Gida',
    sectionVisibility: 'Ganin Sashes',
    seoSettings: 'Saituna na SEO',
    theme: 'Jigo',
    schoolSettings: 'Saituna na makarantar',
    advancedSettings: 'Saituna na ci gaba',
    customCss: 'CSS na Musamman',
    schoolWebsite: 'Yanar Gizon Makaranta',
    questionBank: 'Bankin Tambayoyi',
    active: 'Mai aiki',
    inactive: 'Ba mai aiki ba',
    total: 'Jimla',
    allSubjects: 'Dukkan Batutuwan',
    allClasses: 'Dukkan Rarruna',
    allTopics: 'Dukkan Batutuwa',
    allTypes: 'Dukkan Nau\'i',
    allLevels: 'Dukkan Mataki',
    searchQuestions: 'Nema tambayoyi...',
    dashboard: 'Taswirar Bayani',
    students: 'Mutane',
    teachers: 'Malamai',
    classes: 'Rarruna',
    subjects: 'Batutuwa',
    exams: 'Imtihani',
    homework: 'Aiki na Gida',
    attendance: 'Biso',
    fees: 'Kuɗi',
    reports: 'Rahoto',
    messages: 'Saƙonni',
    announcements: 'Sanarwa',
    calendar: 'Kwamitin',
    timetable: 'Jadawalin lokaci',
    library: 'Maktaba',
    transport: 'Jigawa',
    login: 'Shiga',
    logout: 'Fita',
    register: 'Yi Rajista',
    profile: 'Bayanan Martaba',
    language: 'Harshe',
    beginner: 'Farko',
    intermediate: 'Matsakaici',
    advanced: 'Ci gaba',
    dashboard: 'Taswira',
    home: 'Gida',
    aboutUs: 'Game da mu',
    contact: 'Tuntuɓi',
    learnMore: 'Koyi ƙari',
    applyNow: 'Nemi yanzu',
    portalLogin: 'Shiga Portal',
    poweredBy: 'An ƙaddamar da',
    allRightsReserved: 'An yi rajista.',
  },
  yo: {
    welcome: 'Kuú orú',
    settings: 'Ètò',
    save: 'Fipamò',
    cancel: 'Kọ́silẹ̀',
    delete: 'Parẹ́',
    edit: 'Túntúnsí',
    add: 'Fi kún',
    search: 'Wá',
    filter: 'Yàn',
    export: 'Kó sókò',
    import: 'Wọ inú',
    loading: 'Ń kó yẹ...',
    noData: 'Kò sí data',
    error: 'Àṣìṣẹ́ wáyé',
    success: 'Àṣeyọ́ri',
    confirm: 'Jẹ́rẹ́',
    close: 'Tí',
    back: 'Pẹ̀lẹ́',
    next: 'Ìsàlẹ̀',
    submit: 'Fi sílẹ̀',
    reset: 'Tún bẹ̀rẹ̀',
    view: 'Wò',
    duplicate: 'Ṣe méjì',
    deactivate: 'Kò lè ṣiṣẹ́',
    activate: 'Bẹ̀rẹ̀ sí ṣiṣẹ́',
    refresh: 'Ṣe tuntun',
    publish: 'Tẹ̀síwájú',
    unpublish: 'Kò tẹ̀síwájú',
    saveDraft: 'Fipamò ìwé',
    preview: 'Wò kí o tún wò',
    hidePreview: 'Fìmọ́ kí o tún wò',
    showPreview: 'Hà kí o tún wò',
    generate: 'Ṣe',
    generating: 'Ń ṣe...',
    setup: 'Ṣe ètò',
    bulkImport: 'Wọ inú púpọ̀',
    addQuestion: 'Fi ìbáradì sí',
    deleteSelected: 'Parẹ́ ìyanu',
    deleteAll: 'Parẹ́ gbogbo',
    deactivateQuestion: 'Kò lè ṣiṣẹ́ ìbáradì',
    deactivateSelected: 'Kò lè ṣiṣẹ́ ìbáradì ìyanu',
    deactivateAll: 'Kò lè ṣiṣẹ́ gbogbo ìbáradì',
    dashboard: 'Ìwòran',
    students: 'Akẹ́kọ́',
    teachers: 'Olùkọ́',
    classes: 'Ẹ̀kọ́',
    subjects: 'Ìṣòro',
    home: 'Ilé',
    aboutUs: 'Nípa àwa',
    contact: 'Bá àwa sọ̀rọ̀',
    learnMore: 'Kẹ́kọ̀ó',
    applyNow: 'Bèèrè báyìí',
    portalLogin: 'Wọ inú Portal',
    poweredBy: 'Gbé',
    allRightsReserved: 'Gbogbo ẹ̀tọ́ wa ní pasẹ̀.',
  },
  ig: {
    welcome: 'Nnọọ',
    settings: 'Nhọrụ',
    save: 'Debe',
    cancel: 'Gbochie',
    delete: 'Meechie',
    edit: 'Gbanwe',
    add: 'Tinyekwu',
    search: 'Chọọ',
    filter: 'Nyochaa',
    export: 'Mepụta',
    import: 'Bulite',
    loading: 'Na-ebu...',
    noData: 'Enweghị data',
    error: 'Njem ajọ',
    success: 'Ihe niile',
    confirm: 'Nkwado',
    close: 'Mechie',
    back: 'Laghachi',
    next: 'N\'ihu',
    submit: 'Nyochaa',
    reset: 'Mee ihe niile',
    view: 'Lee',
    duplicate: 'Mee abụọ',
    deactivate: 'Emeghị arụ ọrụ',
    activate: 'Bido arụ ọrụ',
    refresh: 'Mee ihe ọhụrụ',
    publish: 'Pọpụta',
    unpublish: 'Emeghị pọpụta',
    saveDraft: 'Debe akwụkwọ',
    preview: 'Lee tupu',
    hidePreview: 'Zoo lee tupu',
    showPreview: 'Gosi lee tupu',
    generate: 'Mee',
    generating: 'Na-eme...',
    setup: 'Nhazi',
    bulkImport: 'Bulite ọtụtụ',
    addQuestion: 'Tinye ajụjụ',
    deleteSelected: 'Meechie ihe a họrọ',
    deleteAll: 'Meechie ihe niile',
    deactivateQuestion: 'Emeghị arụ ọrụ ajụjụ',
    deactivateSelected: 'Emeghị arụ ọrụ ajụjụ a họrọ',
    deactivateAll: 'Emeghị arụ ọrụ ajụjụ niile',
    dashboard: 'Ihe nlereanya',
    students: 'Ndi nta',
    teachers: 'Ndi nkuzi',
    classes: 'Ogú',
    subjects: 'Isi okwu',
    home: 'Ụlọ',
    aboutUs: 'Banyere anyị',
    contact: 'Kpọtụrụ anyị',
    learnMore: 'Mụta karịa',
    applyNow: 'Nyocha ugbu a',
    portalLogin: 'Banye Portal',
    poweredBy: 'Bulite',
    allRightsReserved: 'Ihe niile niile.',
  },
};

export function t(key: string, lang: string = 'en', params?: Record<string, string | number>): string {
  let result = translations[lang]?.[key] || translations.en[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      result = result.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
    });
  }
  return result;
}
