import {
  type BannerDesignState,
  type TemplatePreset,
  type BannerSizePreset,
  createShape,
} from './types';

function tpl(overrides: Partial<BannerDesignState>, size: BannerSizePreset): Partial<BannerDesignState> {
  return { ...overrides, size };
}

export const BANNER_TEMPLATE_PRESETS: TemplatePreset[] = [
  // ─── Events ───
  {
    name: 'School Event',
    category: 'Events',
    description: 'Bold announcement for school events',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Annual School Festival',
      subtitle: 'A Day of Fun & Learning',
      description: 'Join us for games, performances, and exhibitions',
      backgroundStyle: 'gradient',
      colors: { primary: '#7c3aed', secondary: '#a78bfa', accent: '#fbbf24', text: '#ffffff', textSecondary: '#e0e7ff', bg: '#4c1d95', gradientStart: '#7c3aed', gradientEnd: '#4c1d95' },
      shapes: [createShape('header-band', '#fbbf24'), createShape('footer-band', '#fbbf24')],
    }, 'instagram-post'),
  },
  {
    name: 'Sports Day',
    category: 'Events',
    description: 'Energetic design for sports events',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Sports Day 2025',
      subtitle: 'Compete. Achieve. Inspire.',
      description: 'All students are encouraged to participate',
      backgroundStyle: 'gradient',
      colors: { primary: '#dc2626', secondary: '#f87171', accent: '#ffffff', text: '#ffffff', textSecondary: '#fecaca', bg: '#991b1b', gradientStart: '#dc2626', gradientEnd: '#991b1b' },
      shapes: [createShape('diagonal-band', '#fbbf24')],
    }, 'facebook-post'),
  },
  {
    name: 'Science Fair',
    category: 'Events',
    description: 'Modern look for science exhibitions',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Science Fair 2025',
      subtitle: 'Discover. Experiment. Innovate.',
      description: 'Present your projects and explore the world of science',
      backgroundStyle: 'gradient',
      colors: { primary: '#0891b2', secondary: '#22d3ee', accent: '#fbbf24', text: '#ffffff', textSecondary: '#cffafe', bg: '#164e63', gradientStart: '#0891b2', gradientEnd: '#164e63' },
      shapes: [createShape('corner-top-right', '#22d3ee'), createShape('corner-bottom-left', '#22d3ee')],
    }, 'instagram-post'),
  },
  {
    name: 'Cultural Day',
    category: 'Events',
    description: 'Vibrant celebration of culture',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Cultural Day Celebration',
      subtitle: 'Embracing Our Diversity',
      description: 'Wear your cultural attire and celebrate with us',
      backgroundStyle: 'gradient',
      colors: { primary: '#d97706', secondary: '#fbbf24', accent: '#dc2626', text: '#ffffff', textSecondary: '#fef3c7', bg: '#78350f', gradientStart: '#d97706', gradientEnd: '#78350f' },
      shapes: [createShape('header-band', '#dc2626'), createShape('footer-band', '#dc2626')],
    }, 'facebook-post'),
  },
  {
    name: 'Art Exhibition',
    category: 'Events',
    description: 'Creative and artistic design',
    defaultSize: 'a4-portrait',
    design: tpl({
      title: 'Art Exhibition',
      subtitle: 'Where Creativity Comes Alive',
      description: 'Showcasing student artwork from all grades',
      backgroundStyle: 'gradient',
      colors: { primary: '#c026d3', secondary: '#e879f9', accent: '#fbbf24', text: '#ffffff', textSecondary: '#f5d0fe', bg: '#86198f', gradientStart: '#c026d3', gradientEnd: '#86198f' },
      shapes: [createShape('circle', '#e879f9')],
    }, 'a4-portrait'),
  },

  // ─── Academic ───
  {
    name: 'Graduation',
    category: 'Academic',
    description: 'Elegant graduation ceremony design',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Graduation Ceremony',
      subtitle: 'Class of 2025',
      description: 'Celebrating our graduates and their achievements',
      backgroundStyle: 'gradient',
      colors: { primary: '#1a365d', secondary: '#d4a017', accent: '#ffffff', text: '#ffffff', textSecondary: '#bee3f8', bg: '#0f172a', gradientStart: '#1a365d', gradientEnd: '#0f172a' },
      shapes: [createShape('header-band', '#d4a017'), createShape('footer-band', '#d4a017')],
      fontFamily: '"Playfair Display", serif',
    }, 'facebook-post'),
  },
  {
    name: 'Award Ceremony',
    category: 'Academic',
    description: 'Formal award ceremony banner',
    defaultSize: 'website-hero',
    design: tpl({
      title: 'Award Ceremony',
      subtitle: 'Honoring Excellence',
      description: 'Recognizing outstanding student achievements',
      backgroundStyle: 'gradient',
      colors: { primary: '#1e40af', secondary: '#60a5fa', accent: '#fbbf24', text: '#ffffff', textSecondary: '#dbeafe', bg: '#1e3a5f', gradientStart: '#1e40af', gradientEnd: '#1e3a5f' },
      shapes: [createShape('header-band', '#fbbf24')],
    }, 'website-hero'),
  },
  {
    name: 'Exam Schedule',
    category: 'Academic',
    description: 'Clear exam schedule announcement',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Examination Schedule',
      subtitle: 'Mid-Term Examinations',
      description: 'Prepare well and give your best',
      backgroundStyle: 'solid',
      colors: { primary: '#059669', secondary: '#34d399', accent: '#ffffff', text: '#ffffff', textSecondary: '#d1fae5', bg: '#065f46', gradientStart: '#059669', gradientEnd: '#065f46' },
      shapes: [createShape('header-band', '#34d399')],
    }, 'facebook-post'),
  },
  {
    name: 'Back to School',
    category: 'Academic',
    description: 'Welcome back to school design',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Back to School',
      subtitle: 'New Term, New Beginnings',
      description: 'School reopens on Monday. Be ready!',
      backgroundStyle: 'gradient',
      colors: { primary: '#2563eb', secondary: '#60a5fa', accent: '#fbbf24', text: '#ffffff', textSecondary: '#dbeafe', bg: '#1e40af', gradientStart: '#2563eb', gradientEnd: '#1e40af' },
      shapes: [createShape('header-band', '#fbbf24'), createShape('footer-band', '#fbbf24')],
    }, 'instagram-post'),
  },

  // ─── Social Media ───
  {
    name: 'Instagram Story',
    category: 'Social Media',
    description: 'Optimized for Instagram stories',
    defaultSize: 'instagram-story',
    design: tpl({
      title: 'School Update',
      subtitle: 'Stay Connected',
      description: 'Follow us for the latest news and updates',
      backgroundStyle: 'gradient',
      colors: { primary: '#e11d48', secondary: '#fb7185', accent: '#ffffff', text: '#ffffff', textSecondary: '#fecdd3', bg: '#9f1239', gradientStart: '#e11d48', gradientEnd: '#9f1239' },
      shapes: [createShape('circle', '#fb7185')],
    }, 'instagram-story'),
  },
  {
    name: 'Facebook Promo',
    category: 'Social Media',
    description: 'Promotional Facebook post',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Admissions Open 2025',
      subtitle: 'Give Your Child the Best Education',
      description: 'Limited seats available. Enroll today!',
      backgroundStyle: 'gradient',
      colors: { primary: '#059669', secondary: '#34d399', accent: '#fbbf24', text: '#ffffff', textSecondary: '#d1fae5', bg: '#065f46', gradientStart: '#059669', gradientEnd: '#065f46' },
      shapes: [createShape('header-band', '#fbbf24')],
    }, 'facebook-post'),
  },
  {
    name: 'Twitter Announcement',
    category: 'Social Media',
    description: 'Clean Twitter/X announcement',
    defaultSize: 'twitter-post',
    design: tpl({
      title: 'Important Notice',
      subtitle: '',
      description: 'School will remain closed on Friday due to public holiday.',
      backgroundStyle: 'solid',
      colors: { primary: '#1d4ed8', secondary: '#60a5fa', accent: '#ffffff', text: '#ffffff', textSecondary: '#dbeafe', bg: '#1e40af', gradientStart: '#1e40af', gradientEnd: '#1e3a8a' },
      shapes: [],
      showDescription: true,
    }, 'twitter-post'),
  },

  // ─── Welcome ───
  {
    name: 'New Student Welcome',
    category: 'Welcome',
    description: 'Warm welcome for new students',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Welcome!',
      subtitle: 'New Students 2025',
      description: 'We are thrilled to have you join our family',
      backgroundStyle: 'gradient',
      colors: { primary: '#7c3aed', secondary: '#a78bfa', accent: '#fbbf24', text: '#ffffff', textSecondary: '#ede9fe', bg: '#5b21b6', gradientStart: '#7c3aed', gradientEnd: '#5b21b6' },
      shapes: [createShape('header-band', '#fbbf24'), createShape('footer-band', '#fbbf24')],
    }, 'instagram-post'),
  },
  {
    name: 'Open Day',
    category: 'Welcome',
    description: 'School open day invitation',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Open Day',
      subtitle: 'Come Visit Our Campus',
      description: 'Meet our teachers, tour our facilities, and learn about our programs',
      backgroundStyle: 'gradient',
      colors: { primary: '#0369a1', secondary: '#38bdf8', accent: '#fbbf24', text: '#ffffff', textSecondary: '#e0f2fe', bg: '#0c4a6e', gradientStart: '#0369a1', gradientEnd: '#0c4a6e' },
      shapes: [createShape('header-band', '#38bdf8')],
    }, 'facebook-post'),
  },
  {
    name: 'Admissions Open',
    category: 'Welcome',
    description: 'Admissions announcement',
    defaultSize: 'website-hero',
    design: tpl({
      title: 'Admissions Now Open',
      subtitle: 'Academic Year 2025-2026',
      description: 'Apply now and secure your child\'s future',
      backgroundStyle: 'gradient',
      colors: { primary: '#059669', secondary: '#34d399', accent: '#fbbf24', text: '#ffffff', textSecondary: '#d1fae5', bg: '#064e3b', gradientStart: '#059669', gradientEnd: '#064e3b' },
      shapes: [createShape('header-band', '#fbbf24'), createShape('footer-band', '#fbbf24')],
    }, 'website-hero'),
  },

  // ─── Announcements ───
  {
    name: 'Holiday Notice',
    category: 'Announcements',
    description: 'Holiday/vacation notice',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Holiday Notice',
      subtitle: 'Winter Break',
      description: 'School will be closed from Dec 20 to Jan 5. Classes resume on Jan 6.',
      backgroundStyle: 'solid',
      colors: { primary: '#dc2626', secondary: '#f87171', accent: '#ffffff', text: '#ffffff', textSecondary: '#fecaca', bg: '#991b1b', gradientStart: '#dc2626', gradientEnd: '#991b1b' },
      shapes: [createShape('header-band', '#ffffff')],
    }, 'facebook-post'),
  },
  {
    name: 'Emergency Alert',
    category: 'Announcements',
    description: 'High-visibility emergency alert',
    defaultSize: 'twitter-post',
    design: tpl({
      title: 'URGENT NOTICE',
      subtitle: '',
      description: 'School closed today due to severe weather. Stay safe.',
      backgroundStyle: 'solid',
      colors: { primary: '#dc2626', secondary: '#fbbf24', accent: '#ffffff', text: '#ffffff', textSecondary: '#fecaca', bg: '#7f1d1d', gradientStart: '#dc2626', gradientEnd: '#7f1d1d' },
      shapes: [createShape('header-band', '#fbbf24'), createShape('footer-band', '#fbbf24')],
    }, 'twitter-post'),
  },
  {
    name: 'General Announcement',
    category: 'Announcements',
    description: 'Clean general announcement',
    defaultSize: 'facebook-post',
    design: tpl({
      title: 'Notice to Parents',
      subtitle: 'Parent-Teacher Meeting',
      description: 'PTM scheduled for Saturday. All parents are cordially invited.',
      backgroundStyle: 'solid',
      colors: { primary: '#475569', secondary: '#94a3b8', accent: '#fbbf24', text: '#ffffff', textSecondary: '#e2e8f0', bg: '#334155', gradientStart: '#475569', gradientEnd: '#334155' },
      shapes: [createShape('header-band', '#fbbf24')],
    }, 'facebook-post'),
  },

  // ─── Sports ───
  {
    name: 'Tournament',
    category: 'Sports',
    description: 'Dynamic sports tournament design',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Inter-School Tournament',
      subtitle: 'Football Championship 2025',
      description: 'May the best team win!',
      backgroundStyle: 'gradient',
      colors: { primary: '#16a34a', secondary: '#4ade80', accent: '#fbbf24', text: '#ffffff', textSecondary: '#dcfce7', bg: '#166534', gradientStart: '#16a34a', gradientEnd: '#166534' },
      shapes: [createShape('diagonal-band', '#fbbf24')],
    }, 'instagram-post'),
  },
  {
    name: 'Match Day',
    category: 'Sports',
    description: 'Match day announcement',
    defaultSize: 'twitter-post',
    design: tpl({
      title: 'Match Day!',
      subtitle: 'School vs. Academy',
      description: 'Come support our team!',
      backgroundStyle: 'gradient',
      colors: { primary: '#dc2626', secondary: '#f87171', accent: '#1d4ed8', text: '#ffffff', textSecondary: '#fecaca', bg: '#991b1b', gradientStart: '#dc2626', gradientEnd: '#991b1b' },
      shapes: [createShape('header-band', '#1d4ed8')],
    }, 'twitter-post'),
  },

  // ─── Seasonal ───
  {
    name: 'End of Year',
    category: 'Seasonal',
    description: 'End of academic year celebration',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'End of Year Celebration',
      subtitle: 'What a Wonderful Year!',
      description: 'Thank you students, parents, and staff for an amazing year',
      backgroundStyle: 'gradient',
      colors: { primary: '#d97706', secondary: '#fbbf24', accent: '#ffffff', text: '#ffffff', textSecondary: '#fef3c7', bg: '#92400e', gradientStart: '#d97706', gradientEnd: '#92400e' },
      shapes: [createShape('header-band', '#ffffff'), createShape('footer-band', '#ffffff')],
    }, 'instagram-post'),
  },
  {
    name: 'Christmas',
    category: 'Seasonal',
    description: 'Christmas holiday greetings',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Merry Christmas!',
      subtitle: 'Happy Holidays',
      description: 'Wishing you joy and peace this holiday season',
      backgroundStyle: 'gradient',
      colors: { primary: '#dc2626', secondary: '#16a34a', accent: '#fbbf24', text: '#ffffff', textSecondary: '#fecaca', bg: '#7f1d1d', gradientStart: '#dc2626', gradientEnd: '#166534' },
      shapes: [createShape('corner-top-right', '#16a34a'), createShape('corner-bottom-left', '#16a34a')],
    }, 'instagram-post'),
  },
  {
    name: 'Ramadan / Eid',
    category: 'Seasonal',
    description: 'Ramadan and Eid greetings',
    defaultSize: 'instagram-post',
    design: tpl({
      title: 'Ramadan Mubarak',
      subtitle: 'Wishing You a Blessed Ramadan',
      description: 'May this holy month bring peace and prosperity',
      backgroundStyle: 'gradient',
      colors: { primary: '#059669', secondary: '#d4a017', accent: '#ffffff', text: '#ffffff', textSecondary: '#d1fae5', bg: '#064e3b', gradientStart: '#059669', gradientEnd: '#064e3b' },
      shapes: [createShape('header-band', '#d4a017'), createShape('footer-band', '#d4a017')],
      fontFamily: '"Playfair Display", serif',
    }, 'instagram-post'),
  },
];
