import { TemplatePreset, DEFAULT_CERTIFICATE_DESIGN } from './types';

export const CERTIFICATE_TEMPLATES: TemplatePreset[] = [
  {
    name: 'Classic Achievement',
    type: 'ACHIEVEMENT',
    category: 'Classic',
    description: 'Traditional gold-accented certificate with double border',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Classic Achievement',
      type: 'ACHIEVEMENT',
      colors: {
        primary: '#1a365d', secondary: '#d4a017', accent: '#f5f0e8',
        text: '#1e293b', textSecondary: '#64748b', headerBg: '#1a365d', bg: '#ffffff', border: '#d4a017',
      },
      foilStyle: 'gold',
      fontFamily: '"Times New Roman", serif',
      borderStyle: 'double',
      backgroundStyle: 'solid',
      certificateTitle: 'Certificate of Achievement',
      showBorderArt: true,
    },
  },
  {
    name: 'Modern Completion',
    type: 'COMPLETION',
    category: 'Modern',
    description: 'Clean sans-serif design with colored accent bar',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Modern Completion',
      type: 'COMPLETION',
      colors: {
        primary: '#059669', secondary: '#34d399', accent: '#f0fdf4',
        text: '#1e293b', textSecondary: '#64748b', headerBg: '#059669', bg: '#ffffff', border: '#059669',
      },
      foilStyle: 'none',
      fontFamily: '"Helvetica Neue", sans-serif',
      borderStyle: 'solid',
      backgroundStyle: 'gradient',
      gradientStart: '#ffffff',
      gradientEnd: '#f0fdf4',
      certificateTitle: 'Certificate of Completion',
      purposeText: 'This is to certify that',
      completionText: 'has successfully completed the program of study',
      honorText: '',
      showSeal: false,
      showBorderArt: true,
      showWatermark: false,
      borderWidth: 2,
    },
  },
  {
    name: 'Elegant Testimonial',
    type: 'TESTIMONIAL',
    category: 'Elegant',
    description: 'Serif font with filigree border and cream background',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Elegant Testimonial',
      type: 'TESTIMONIAL',
      colors: {
        primary: '#7c2d12', secondary: '#d4a017', accent: '#fef3c7',
        text: '#451a03', textSecondary: '#92400e', headerBg: '#7c2d12', bg: '#fffbeb', border: '#d4a017',
      },
      foilStyle: 'gold',
      fontFamily: '"Palatino Linotype", serif',
      borderStyle: 'filigree',
      backgroundStyle: 'solid',
      certificateTitle: 'Testimonial of Character',
      purposeText: 'This is to certify that',
      completionText: 'has been a student of this institution and is known to be of good character and conduct.',
      honorText: '',
      customMessage: 'We commend {{possessive}} diligence, discipline, and positive contribution to the school community. We wish {{object}} success in {{possessive}} future endeavors.',
      showStudentPhoto: false,
      showGrade: false,
      showSubjects: false,
      showAttendance: false,
      showSeal: true,
      showBorderArt: true,
      showWatermark: true,
      watermarkText: 'TESTIMONIAL',
    },
  },
  {
    name: 'Graduation Diploma',
    type: 'GRADUATION',
    category: 'Premium',
    description: 'Ornate border with gold foil, seal, and premium styling',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Graduation Diploma',
      type: 'GRADUATION',
      colors: {
        primary: '#1e3a5f', secondary: '#c8a84e', accent: '#f0ebe0',
        text: '#1a1a2e', textSecondary: '#4a5568', headerBg: '#1e3a5f', bg: '#faf8f5', border: '#c8a84e',
      },
      foilStyle: 'gold',
      fontFamily: '"Playfair Display", serif',
      titleFontSize: '3xl',
      borderStyle: 'ornate',
      borderWidth: 4,
      backgroundStyle: 'gradient',
      gradientStart: '#faf8f5',
      gradientEnd: '#f0ebe0',
      backgroundPattern: 'damask',
      certificateTitle: 'Diploma of Graduation',
      purposeText: 'The Faculty and Administration hereby confer upon',
      completionText: 'who has successfully fulfilled all requirements for graduation',
      honorText: 'with Honors',
      customMessage: 'In recognition of {{possessive}} dedication to academic excellence and personal growth, we confer this diploma with all the rights and privileges pertaining thereto.',
      showSeal: true,
      showBorderArt: true,
      showWatermark: true,
      watermarkText: 'GRADUATE',
      showSubjects: true,
      showGrade: true,
      sealPosition: 'center',
    },
  },
  {
    name: 'Merit Award',
    type: 'MERIT',
    category: 'Classic',
    description: 'Academic excellence certificate with laurel border',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Merit Award',
      type: 'MERIT',
      colors: {
        primary: '#0d4f2b', secondary: '#c8a84e', accent: '#f0f7f3',
        text: '#1e293b', textSecondary: '#4a7c59', headerBg: '#0d4f2b', bg: '#ffffff', border: '#c8a84e',
      },
      foilStyle: 'gold',
      fontFamily: '"Garamond", serif',
      borderStyle: 'laurel',
      certificateTitle: 'Merit Award',
      purposeText: 'This award is presented to',
      completionText: 'in recognition of outstanding academic performance and exemplary conduct',
      honorText: 'First Class Honors',
      showSubjects: true,
      showGrade: true,
      showAttendance: false,
      showSeal: true,
      showBorderArt: true,
      watermarkText: 'MERIT',
    },
  },
  {
    name: 'Sports Achievement',
    type: 'SPORTS',
    category: 'Modern',
    description: 'Dynamic angled design with medal motifs',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Sports Achievement',
      type: 'SPORTS',
      colors: {
        primary: '#dc2626', secondary: '#fbbf24', accent: '#fef2f2',
        text: '#1e293b', textSecondary: '#6b7280', headerBg: '#dc2626', bg: '#ffffff', border: '#fbbf24',
      },
      foilStyle: 'bronze',
      fontFamily: '"Montserrat", sans-serif',
      borderStyle: 'artdeco',
      backgroundStyle: 'gradient',
      gradientStart: '#ffffff',
      gradientEnd: '#fef2f2',
      backgroundPattern: 'confetti',
      certificateTitle: 'Sports Achievement Award',
      purposeText: 'Presented to',
      completionText: 'for exceptional performance and sportsmanship',
      honorText: 'Champion',
      customMessage: 'Your dedication, team spirit, and athletic excellence have made our school proud. Continue to strive for greatness!',
      showGrade: false,
      showSubjects: false,
      showAttendance: false,
      showStudentPhoto: true,
      showSeal: false,
      showBorderArt: true,
      watermarkText: 'SPORTS',
      showWatermark: false,
    },
  },
  {
    name: 'Transfer Certificate',
    type: 'TRANSFER',
    category: 'Administrative',
    description: 'Formal document with school seal and verification QR',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Transfer Certificate',
      type: 'TRANSFER',
      colors: {
        primary: '#1e3a5f', secondary: '#475569', accent: '#f1f5f9',
        text: '#1e293b', textSecondary: '#475569', headerBg: '#1e3a5f', bg: '#ffffff', border: '#475569',
      },
      foilStyle: 'none',
      fontFamily: '"Times New Roman", serif',
      borderStyle: 'double',
      certificateTitle: 'Transfer Certificate',
      purposeText: 'This is to certify that',
      completionText: 'was a student of this institution from {{session}} and is hereby transferred.',
      honorText: '',
      customMessage: '{{possessive}} conduct during {{possessive}} stay in this institution has been {{grade}}. We wish {{object}} success in {{possessive}} future academic pursuits.',
      showStudentPhoto: false,
      showGrade: false,
      showSubjects: false,
      showAttendance: true,
      showSeal: true,
      showBorderArt: true,
      showQRCode: true,
      watermarkText: 'TRANSFER',
      sealPosition: 'bottom',
    },
  },
  {
    name: 'Participation Fun',
    type: 'PARTICIPATION',
    category: 'Modern',
    description: 'Colorful design with geometric pattern',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Participation Fun',
      type: 'PARTICIPATION',
      colors: {
        primary: '#7c3aed', secondary: '#a78bfa', accent: '#f5f3ff',
        text: '#1e293b', textSecondary: '#6d28d9', headerBg: '#7c3aed', bg: '#ffffff', border: '#a78bfa',
      },
      foilStyle: 'silver',
      fontFamily: '"Lato", sans-serif',
      borderStyle: 'vintage',
      backgroundStyle: 'gradient',
      gradientStart: '#ffffff',
      gradientEnd: '#f5f3ff',
      backgroundPattern: 'geometric',
      certificateTitle: 'Certificate of Participation',
      purposeText: 'This certificate is proudly presented to',
      completionText: 'for active participation in',
      honorText: '',
      customMessage: 'Your enthusiasm and engagement made this event truly special. Thank you for being a part of it!',
      showGrade: false,
      showSubjects: false,
      showAttendance: false,
      showSeal: false,
      showBorderArt: true,
      showWatermark: false,
      showStudentPhoto: false,
      showHonorText: false,
    },
  },
  {
    name: 'Promotion Certificate',
    type: 'PROMOTION',
    category: 'Administrative',
    description: 'Celebratory design for student promotion',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Promotion Certificate',
      type: 'PROMOTION',
      colors: {
        primary: '#0369a1', secondary: '#38bdf8', accent: '#f0f9ff',
        text: '#1e293b', textSecondary: '#0369a1', headerBg: '#0369a1', bg: '#ffffff', border: '#38bdf8',
      },
      foilStyle: 'silver',
      fontFamily: '"Open Sans", sans-serif',
      borderStyle: 'filigree',
      certificateTitle: 'Promotion Certificate',
      purposeText: 'This certifies that',
      completionText: 'has been promoted to the next class',
      honorText: '',
      customMessage: 'Congratulations on your hard work and academic progress. We are confident you will continue to excel!',
      showGrade: true,
      showSubjects: false,
      showAttendance: false,
      showSeal: true,
      showBorderArt: true,
      watermarkText: 'PROMOTED',
    },
  },
  {
    name: 'Appreciation Award',
    type: 'APPRECIATION',
    category: 'Elegant',
    description: 'Warm design with gratitude-focused typography',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Appreciation Award',
      type: 'APPRECIATION',
      colors: {
        primary: '#b45309', secondary: '#f59e0b', accent: '#fffbeb',
        text: '#1e293b', textSecondary: '#92400e', headerBg: '#b45309', bg: '#fffdf0', border: '#f59e0b',
      },
      foilStyle: 'gold',
      fontFamily: '"Georgia", serif',
      borderStyle: 'vintage',
      backgroundStyle: 'solid',
      certificateTitle: 'Certificate of Appreciation',
      purposeText: 'With heartfelt gratitude, we thank',
      completionText: 'for {{possessive}} invaluable contribution and dedicated service',
      honorText: '',
      customMessage: 'Your selfless efforts and commitment have made a lasting impact on our community. We are deeply grateful for your support.',
      showGrade: false,
      showSubjects: false,
      showAttendance: false,
      showStudentPhoto: false,
      showSeal: true,
      showBorderArt: true,
      showWatermark: true,
      watermarkText: 'THANK YOU',
      sealPosition: 'center',
    },
  },
  {
    name: 'Internship Completion',
    type: 'INTERNSHIP',
    category: 'Modern',
    description: 'Professional design for industrial training certificates',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Internship Completion',
      type: 'INTERNSHIP',
      colors: {
        primary: '#0f766e', secondary: '#14b8a6', accent: '#f0fdfa',
        text: '#1e293b', textSecondary: '#0f766e', headerBg: '#0f766e', bg: '#ffffff', border: '#14b8a6',
      },
      foilStyle: 'none',
      fontFamily: '"Helvetica Neue", sans-serif',
      borderStyle: 'solid',
      backgroundStyle: 'gradient',
      gradientStart: '#ffffff',
      gradientEnd: '#f0fdfa',
      certificateTitle: 'Internship Completion Certificate',
      purposeText: 'This is to certify that',
      completionText: 'has successfully completed an internship program',
      honorText: '',
      customMessage: 'During this period, {{subject}} demonstrated professionalism, dedication, and technical competence.',
      showGrade: false,
      showSubjects: false,
      showAttendance: true,
      showSeal: false,
      showBorderArt: true,
      showWatermark: false,
      showStudentPhoto: true,
    },
  },
  {
    name: 'Simple Elegance',
    type: 'GENERAL',
    category: 'Simple',
    description: 'Clean minimal design suitable for any occasion',
    design: {
      ...DEFAULT_CERTIFICATE_DESIGN,
      name: 'Simple Elegance',
      type: 'GENERAL',
      colors: {
        primary: '#334155', secondary: '#64748b', accent: '#f1f5f9',
        text: '#1e293b', textSecondary: '#64748b', headerBg: '#334155', bg: '#ffffff', border: '#94a3b8',
      },
      foilStyle: 'none',
      fontFamily: '"Lato", sans-serif',
      borderStyle: 'solid',
      borderWidth: 1,
      backgroundStyle: 'solid',
      certificateTitle: 'Certificate',
      purposeText: 'Presented to',
      completionText: '',
      honorText: '',
      customMessage: '',
      showSchoolLogo: true,
      showSchoolName: true,
      showStudentPhoto: false,
      showStudentName: true,
      showCertificateTitle: true,
      showPurposeText: true,
      showCompletionText: false,
      showHonorText: false,
      showDate: true,
      showStudentDetails: true,
      showSeal: false,
      showLeftSignature: true,
      showRightSignature: false,
      showQRCode: false,
      showBackgroundPattern: false,
      showBorderArt: false,
      showWatermark: false,
      showCustomMessage: false,
      showFooter: true,
      showGrade: false,
      showAttendance: false,
      showSubjects: false,
      showCertificateNumber: true,
      showVerificationCode: false,
      watermarkText: '',
      sealPosition: 'center',
    },
  },
];

export function getTemplatesByType(type: string): TemplatePreset[] {
  return CERTIFICATE_TEMPLATES.filter(t => t.type === type);
}

export function getTemplatesByCategory(category: string): TemplatePreset[] {
  return CERTIFICATE_TEMPLATES.filter(t => t.category === category);
}
