export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  category: string;
  orientation: 'landscape' | 'portrait';
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    textSecondary: string;
    headerBg: string;
    bg: string;
    gradientFrom?: string;
    gradientTo?: string;
  };
  backgroundType: string;
  fontFamily: string;
  fontSize: string;
  showPhoto: boolean;
  showLogo: boolean;
  showQRCode: boolean;
  showBarcode: boolean;
  showSignature: boolean;
  showWatermark: boolean;
  showMotto: boolean;
  showExpiryDate: boolean;
  showIssueDate: boolean;
  qrPosition: 'front' | 'back' | 'both';
  backLayoutType: 'standard' | 'minimal' | 'detailed';
  showEmergencyInfo: boolean;
  showMedicalInfo: boolean;
  showTerms: boolean;
  showSignatory: boolean;
  showSchoolInfo: boolean;
}

export const DEFAULT_TEMPLATES: TemplatePreset[] = [
  {
    id: 'modern-school',
    name: 'Modern School',
    description: 'Clean, contemporary design with bold header and centered photo. Perfect for modern schools.',
    category: 'School',
    orientation: 'landscape',
    colors: {
      primary: '#059669',
      secondary: '#FFFFFF',
      accent: '#fbbf24',
      text: '#1e293b',
      textSecondary: '#64748b',
      headerBg: '#059669',
      bg: '#ffffff',
      gradientFrom: '#059669',
      gradientTo: '#34d399',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'international',
    name: 'International School',
    description: 'Sophisticated layout with elegant typography and subtle gradients. Suits international/bilingual schools.',
    category: 'School',
    orientation: 'portrait',
    colors: {
      primary: '#1d4ed8',
      secondary: '#FFFFFF',
      accent: '#f59e0b',
      text: '#1e3a5f',
      textSecondary: '#6b7280',
      headerBg: '#1d4ed8',
      bg: '#ffffff',
      gradientFrom: '#1d4ed8',
      gradientTo: '#60a5fa',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'detailed',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'university',
    name: 'University Premium',
    description: 'Academic-style card with classic serif-inspired layout. Great for universities and tertiary institutions.',
    category: 'Academic',
    orientation: 'landscape',
    colors: {
      primary: '#7c3aed',
      secondary: '#faf5ff',
      accent: '#c4b5fd',
      text: '#2e1065',
      textSecondary: '#7c3aed',
      headerBg: '#7c3aed',
      bg: '#ffffff',
      gradientFrom: '#7c3aed',
      gradientTo: '#a78bfa',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'lg',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'detailed',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'corporate-staff',
    name: 'Corporate Staff',
    description: 'Professional corporate design with sleek lines and business-appropriate styling.',
    category: 'Staff',
    orientation: 'landscape',
    colors: {
      primary: '#334155',
      secondary: '#FFFFFF',
      accent: '#0ea5e9',
      text: '#0f172a',
      textSecondary: '#64748b',
      headerBg: '#334155',
      bg: '#ffffff',
      gradientFrom: '#334155',
      gradientTo: '#64748b',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: false,
    showExpiryDate: true,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: false,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'minimal',
    name: 'Minimal Clean',
    description: 'Ultra-minimalist design with plenty of whitespace. Focus on essential information only.',
    category: 'Minimal',
    orientation: 'landscape',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
      accent: '#ffffff',
      text: '#111827',
      textSecondary: '#6b7280',
      headerBg: '#000000',
      bg: '#ffffff',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'sm',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: false,
    showWatermark: false,
    showMotto: false,
    showExpiryDate: false,
    showIssueDate: false,
    qrPosition: 'back',
    backLayoutType: 'minimal',
    showEmergencyInfo: false,
    showMedicalInfo: false,
    showTerms: true,
    showSignatory: false,
    showSchoolInfo: false,
  },
  {
    id: 'premium-executive',
    name: 'Premium Executive',
    description: 'High-end executive design with gold accents and premium finish. For VIP/executive cards.',
    category: 'Premium',
    orientation: 'portrait',
    colors: {
      primary: '#92400e',
      secondary: '#fffbeb',
      accent: '#f59e0b',
      text: '#451a03',
      textSecondary: '#92400e',
      headerBg: '#92400e',
      bg: '#fffbeb',
      gradientFrom: '#92400e',
      gradientTo: '#d97706',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'lg',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: true,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'detailed',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'classic-academic',
    name: 'Classic Academic',
    description: 'Traditional school ID design with heritage feel. Timeless and professional.',
    category: 'Academic',
    orientation: 'landscape',
    colors: {
      primary: '#991b1b',
      secondary: '#fef2f2',
      accent: '#fca5a5',
      text: '#450a0a',
      textSecondary: '#991b1b',
      headerBg: '#991b1b',
      bg: '#fef2f2',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'contemporary',
    name: 'Contemporary Edge',
    description: 'Bold, modern design with asymmetric elements and vibrant color blocking.',
    category: 'Modern',
    orientation: 'portrait',
    colors: {
      primary: '#0891b2',
      secondary: '#ecfeff',
      accent: '#2dd4bf',
      text: '#164e63',
      textSecondary: '#0e7490',
      headerBg: '#0891b2',
      bg: '#ffffff',
      gradientFrom: '#0891b2',
      gradientTo: '#22d3ee',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Modern glass-effect design with frosted background and subtle transparency.',
    category: 'Modern',
    orientation: 'landscape',
    colors: {
      primary: '#6366f1',
      secondary: '#eef2ff',
      accent: '#a5b4fc',
      text: '#1e1b4b',
      textSecondary: '#6366f1',
      headerBg: '#6366f1',
      bg: '#ffffff',
      gradientFrom: '#6366f1',
      gradientTo: '#818cf8',
    },
    backgroundType: 'glass',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'gradient-bold',
    name: 'Gradient Bold',
    description: 'Vibrant gradient background that makes colors pop. Eye-catching and memorable.',
    category: 'Bold',
    orientation: 'portrait',
    colors: {
      primary: '#dc2626',
      secondary: '#fef2f2',
      accent: '#fcd34d',
      text: '#7f1d1d',
      textSecondary: '#dc2626',
      headerBg: '#dc2626',
      bg: '#ffffff',
      gradientFrom: '#dc2626',
      gradientTo: '#fb7185',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'traditional',
    name: 'Traditional School',
    description: 'Classic green and white school ID design. Clean, recognizable, and professional.',
    category: 'School',
    orientation: 'landscape',
    colors: {
      primary: '#15803d',
      secondary: '#f0fdf4',
      accent: '#86efac',
      text: '#14532d',
      textSecondary: '#15803d',
      headerBg: '#15803d',
      bg: '#ffffff',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'sports-academy',
    name: 'Sports Academy',
    description: 'Dynamic design with energetic colors suited for sports academies and athletic programs.',
    category: 'Specialized',
    orientation: 'landscape',
    colors: {
      primary: '#ea580c',
      secondary: '#fff7ed',
      accent: '#fdba74',
      text: '#431407',
      textSecondary: '#ea580c',
      headerBg: '#ea580c',
      bg: '#fff7ed',
      gradientFrom: '#ea580c',
      gradientTo: '#f97316',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'lg',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'primary-school',
    name: 'Primary School Fun',
    description: 'Colorful and friendly design with rounded elements. Perfect for elementary/primary schools.',
    category: 'School',
    orientation: 'portrait',
    colors: {
      primary: '#f43f5e',
      secondary: '#fff1f2',
      accent: '#fcd34d',
      text: '#881337',
      textSecondary: '#f43f5e',
      headerBg: '#f43f5e',
      bg: '#ffffff',
      gradientFrom: '#f43f5e',
      gradientTo: '#fb7185',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: false,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: false,
    qrPosition: 'front',
    backLayoutType: 'minimal',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: false,
    showSignatory: false,
    showSchoolInfo: true,
  },
  {
    id: 'secondary-school',
    name: 'Secondary School',
    description: 'Mature design appropriate for high school students with balanced information hierarchy.',
    category: 'School',
    orientation: 'landscape',
    colors: {
      primary: '#0d9488',
      secondary: '#f0fdfa',
      accent: '#5eead4',
      text: '#134e4a',
      textSecondary: '#0d9488',
      headerBg: '#0d9488',
      bg: '#ffffff',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'science-tech',
    name: 'Science & Technology',
    description: 'Tech-forward design with blue/indigo palette. Great for STEM-focused institutions.',
    category: 'Specialized',
    orientation: 'portrait',
    colors: {
      primary: '#2563eb',
      secondary: '#eff6ff',
      accent: '#93c5fd',
      text: '#1e3a5f',
      textSecondary: '#2563eb',
      headerBg: '#2563eb',
      bg: '#ffffff',
      gradientFrom: '#2563eb',
      gradientTo: '#60a5fa',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'detailed',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'arts-culture',
    name: 'Arts & Culture',
    description: 'Creative design with warm purple/magenta palette. Perfect for arts and humanities schools.',
    category: 'Specialized',
    orientation: 'landscape',
    colors: {
      primary: '#c026d3',
      secondary: '#fdf4ff',
      accent: '#e879f9',
      text: '#4a044e',
      textSecondary: '#c026d3',
      headerBg: '#c026d3',
      bg: '#fdf4ff',
      gradientFrom: '#c026d3',
      gradientTo: '#d946ef',
    },
    backgroundType: 'gradient',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'islamic-school',
    name: 'Islamic School',
    description: 'Elegant design with green accents and Arabic-calligraphy-friendly layout. Suitable for Islamic schools.',
    category: 'Specialized',
    orientation: 'landscape',
    colors: {
      primary: '#059669',
      secondary: '#f0fdf4',
      accent: '#fbbf24',
      text: '#064e3b',
      textSecondary: '#059669',
      headerBg: '#059669',
      bg: '#f0fdf4',
      gradientFrom: '#059669',
      gradientTo: '#34d399',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'military-discipline',
    name: 'Military/Discipline',
    description: 'Structured, authoritative design with dark tones and clean lines. For military-style institutions.',
    category: 'Specialized',
    orientation: 'portrait',
    colors: {
      primary: '#1e293b',
      secondary: '#f8fafc',
      accent: '#eab308',
      text: '#0f172a',
      textSecondary: '#475569',
      headerBg: '#1e293b',
      bg: '#ffffff',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: true,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'back',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
  {
    id: 'custom-blank',
    name: 'Custom Blank',
    description: 'Empty canvas with default styling. Start from scratch and build your own design.',
    category: 'Custom',
    orientation: 'landscape',
    colors: {
      primary: '#6366f1',
      secondary: '#ffffff',
      accent: '#a5b4fc',
      text: '#1e1b4b',
      textSecondary: '#6366f1',
      headerBg: '#6366f1',
      bg: '#ffffff',
    },
    backgroundType: 'solid',
    fontFamily: 'Inter',
    fontSize: 'md',
    showPhoto: true,
    showLogo: true,
    showQRCode: true,
    showBarcode: false,
    showSignature: true,
    showWatermark: true,
    showMotto: true,
    showExpiryDate: false,
    showIssueDate: true,
    qrPosition: 'front',
    backLayoutType: 'standard',
    showEmergencyInfo: true,
    showMedicalInfo: true,
    showTerms: true,
    showSignatory: true,
    showSchoolInfo: true,
  },
];

export function getTemplateById(id: string): TemplatePreset | undefined {
  return DEFAULT_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): TemplatePreset[] {
  return DEFAULT_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateCategories(): string[] {
  return [...new Set(DEFAULT_TEMPLATES.map((t) => t.category))];
}
